name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  lint-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Tool versions
        uses: wistia/parse-tool-versions@v2.1.1
        with:
          prefix: TOOL_VERSION_

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.TOOL_VERSION_GO }}

      - name: Lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: ${{ env.TOOL_VERSION_GOLANGCI_LINT }}

  lint-tf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Tool versions
        uses: wistia/parse-tool-versions@v2.1.1
        with:
          prefix: TOOL_VERSION_

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TOOL_VERSION_TERRAFORM }}

      - name: Lint
        run: |
          terraform fmt -recursive -check

  # lint-docs:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Tool versions
  #       uses: wistia/parse-tool-versions@v2.1.1
  #       with:
  #         prefix: TOOL_VERSION_

  #     - name: Setup Go
  #       uses: actions/setup-go@v5
  #       with:
  #         go-version: ${{ env.TOOL_VERSION_GO }}

  #     - name: Setup tfplugindocs
  #       run: |
  #         go get github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs
  #         go install github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs

  #     - name: Lint
  #       run: |
  #         tfplugindocs validate

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Tool versions
        uses: wistia/parse-tool-versions@v2.1.1
        with:
          prefix: TOOL_VERSION_

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.TOOL_VERSION_GO }}

      - name: Test
        run: |
          go test ./internal/...
